### ISSUE TITLE
Implement AirseekerV2 data feed update loop

### ISSUE THREAD

**Issue by vponline** [api3dao/airseeker-v2#15]
Implement the main loop for the AirseekerV2 which will contain RPC and API calls (#16).

**Comment by Siegrift** [comment]
This issue is way too big considering the complexity of the data feed update loop.I'll split it into smaller ones and this issue can then be closed.

**Comment by Siegrift** [comment]
I've split this into a multiple issues:
- https://github.com/api3dao/airseeker-v2/issues/34
- https://github.com/api3dao/airseeker-v2/issues/35
- https://github.com/api3dao/airseeker-v2/issues/17 (existing one)
- https://github.com/api3dao/airseeker-v2/issues/18 (existing one)
- https://github.com/api3dao/airseeker-v2/issues/36

The first one blocks the others, because it defines the structure of the loop. Other should be done in order, but not necessarily.
